# Generated by Django 6.0.5 on 2026-05-22 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GovService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Xizmat nomi')),
                ('keywords', models.TextField(help_text="Vergul bilan ajratilgan kalit so'zlar (masalan: guvohnoma, tug'ilish, bola)")),
                ('instructions', models.TextField(help_text="Bosqichma-bosqich my.gov.uz yo'riqnomasi")),
            ],
            options={
                'verbose_name': 'Davlat xizmati',
                'verbose_name_plural': 'Davlat xizmatlari',
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_ai', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
