# Generated by Django 6.0.5 on 2026-05-22 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0002_govservice_chatmessage'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
